service: billing-notifier

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: ap-northeast-1
  deploymentBucket: serverless-upload-ap-northeast-1
  versionFunctions: false
  variableSyntax: "\\${{([\\s\\S]+?)}}"

  iamRoleStatements:
    - Effect: Allow
      Resource:
        Fn::Join: [":", [ "arn:aws:codebuild", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "project/billing-notifier" ]]
      Action:
        - codebuild:StartBuild
        - codebuild:BatchGetBuilds
    - Effect: Allow
      Resource: "arn:aws:s3:::${{self:service}}"
      Action:
        - "s3:List*"
        - s3:GetObject
    - Effect: Allow
      Resource: "arn:aws:s3:::${{self:service}}/*"
      Action:
        - "s3:Get*"
        - s3:PutObject

functions:
  kicker:
    handler: handler.kicker
  checker:
    handler: handler.status_getter
  etc:
    handler: handler.etc
    environment:
      ETC_BILLING_NOTIFIER_SLACK_WEBHOOK_URL: "${{file(kms.js):kms.ETC_BILLING_NOTIFIER_SLACK_WEBHOOK_URL}}"
  viewcard:
    handler: handler.viewcard
    environment:
      ETC_BILLING_NOTIFIER_SLACK_WEBHOOK_URL: "${{file(kms.js):kms.ETC_BILLING_NOTIFIER_SLACK_WEBHOOK_URL}}"

resources:
  Resources:
    ## override
    IamRoleLambdaExecution:
      Properties:
        RoleName: "${{self:service}}-exec"

    IamRoleStateMachineExecution:
      Type: AWS::IAM::Role
      Properties:
        RoleName: "${{self:service}}-state"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal: { Service: "states.ap-northeast-1.amazonaws.com" }
              Action: sts:AssumeRole
        Policies:
          - PolicyName: "${{self:service}}-exec-policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action: 
                    - lambda:InvokeFunction
                  Resource:
                    - { Fn::GetAtt: [KickerLambdaFunction, Arn] }
                    - { Fn::GetAtt: [CheckerLambdaFunction, Arn] }
                    - { Fn::GetAtt: [ViewcardLambdaFunction, Arn] }
                    - { Fn::GetAtt: [EtcLambdaFunction, Arn] }

    IamRoleCodeBuildExecution:
      Type: AWS::IAM::Role
      Properties:
        RoleName: "${{self:service}}-codebuild"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: codebuild.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: "${{self:service}}-codebuild-policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Resource:
                    - "arn:aws:s3:::${{self:service}}/*"
                  Action:
                    - s3:PutObject
                - Effect: Allow
                  Resource: "*"
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                - Effect: Allow
                  Resource:
                    Fn::Join: [":", [ "arn:aws:dynamodb", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "table/credential-store" ]]
                  Action:
                    - dynamodb:BatchGetItem
                    - dynamodb:BatchWriteItem
                    - dynamodb:DeleteItem
                    - dynamodb:DescribeReservedCapacity
                    - dynamodb:DescribeReservedCapacityOfferings
                    - dynamodb:DescribeStream
                    - dynamodb:DescribeTable
                    - dynamodb:GetItem
                    - dynamodb:GetRecords
                    - dynamodb:GetShardIterator
                    - dynamodb:ListStreams
                    - dynamodb:ListTables
                    - dynamodb:PutItem
                    - dynamodb:Query
                    - dynamodb:Scan
                    - dynamodb:UpdateItem
                - Effect: Allow
                  Resource:
                    Fn::Join: [":", [ "arn:aws:kms", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "key/${{file(kms.js):kms.GENERAL_CREDSTASH_KMS_ID}}" ]]
                  Action:
                    - kms:Encrypt
                    - kms:Decrypt
                    - kms:ReEncrypt*
                    - kms:GenerateDataKey*
                    - kms:DescribeKey

    ResultStoreBucket:
      Type: AWS::S3::Bucket
      Properties:
       BucketName: "${{self:service}}"

    CodeBuildPoller:
      Type: AWS::StepFunctions::StateMachine
      Properties:
        RoleArn:
          Fn::GetAtt: [ IamRoleStateMachineExecution, Arn ]   
        DefinitionString: 
          Fn::Sub: |-
            {
              "Comment": "Polling codebuild running",
              "StartAt": "JobMain",
              "States": {
                "JobMain":    { "Type": "Task", "Resource": "${KickerLambdaFunction.Arn}",  "Next": "JobCheck" },
                "JobCheck":   { "Type": "Task", "Resource": "${CheckerLambdaFunction.Arn}", "Next": "JobPoller" },
                "JobPoller":  {
                  "Type": "Choice",
                  "Choices": [
                    { "Variable": "$.buildStatus", "StringEquals": "SUCCEEDED",   "Next": "JobSuccess" },
                    { "Variable": "$.buildStatus", "StringEquals": "IN_PROGRESS", "Next": "JobWait" }
                  ]
                },
                "JobWait":    { "Type": "Wait", "Seconds": 5, "Next": "JobCheck" },
                "JobSuccess": { "Type": "Task", "Resource": "${EtcLambdaFunction.Arn}", "End": true }
              }
            }

    BillingSiteParser:
      Type: AWS::CodeBuild::Project
      Properties:
        Name: "${{self:service}}"
        Description: ETC meisai site parser
        Artifacts:
          Type: S3
          Location: billing-notifier
          Name: codebuild_result
          Packaging: NONE
          NamespaceType: NONE
        Environment:
          Type: LINUX_CONTAINER
          Image: "celeron1ghz/nightmare"
          ComputeType: BUILD_GENERAL1_SMALL
        ServiceRole: { Ref: IamRoleCodeBuildExecution }
        Source:
          Type: GITHUB
          Location: "https://github.com/celeron1ghz/billing-notifier.git"
        TimeoutInMinutes: 10
